services:
  app:
    container_name: housy-backend 
    image: housy-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bun start:dev 
    volumes:
      - "./:/app"
    mem_limit: 2G
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - housy
    ports:
      - "8000:8000"
  db:
    image: postgres
    container_name: housy-db
    ports:
      - "5432:5432"
    networks:
      - housy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  housy:
    driver: bridge
