services:
  api:
    container_name: gestora-backend 
    image: gestora-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bun start:dev 
    volumes:
      - "./:/api"
    mem_limit: 2G
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - gestora 
    ports:
      - "8000:8000"
  db:
    image: postgres
    container_name: gestora-db
    ports:
      - "5432:5432"
    networks:
      - gestora 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

networks:
  gestora:
    driver: bridge
