FROM node:22.15
# Set the working directory
WORKDIR /app
# Copy package.json and bun.lockb
COPY package.json bun.lockb ./
# Install dependencies
RUN npm install -g bun
RUN bun install 

# Copy the rest of the application code
COPY . .
EXPOSE 8000
